# Generated by Django 2.0 on 2018-01-26 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0008_remove_studentprofile_date_of_birth'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=5)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile')),
            ],
        ),
    ]
