# Generated by Django 2.0 on 2018-01-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_studentprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=10, null=True),
        ),
    ]
