# Generated by Django 2.0 on 2018-01-26 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0008_remove_studentprofile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyingCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('section', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedCouse1st',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('section', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedCouse2nd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('section', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedCouse3rd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('section', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedCouse4th',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('section', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedCouse5th',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('section', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedCouse6th',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('section', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedCouse7th',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('section', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedCouse8th',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('section', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=256)),
                ('contact_hour', models.IntegerField()),
                ('credit_hour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prerequisite', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TakenCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10)),
                ('section', models.CharField(max_length=5)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile')),
            ],
        ),
        migrations.AddField(
            model_name='completedcouse8th',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList'),
        ),
        migrations.AddField(
            model_name='completedcouse8th',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse8th',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse7th',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList'),
        ),
        migrations.AddField(
            model_name='completedcouse7th',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse7th',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse6th',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList'),
        ),
        migrations.AddField(
            model_name='completedcouse6th',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse6th',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse5th',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList'),
        ),
        migrations.AddField(
            model_name='completedcouse5th',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse5th',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse4th',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList'),
        ),
        migrations.AddField(
            model_name='completedcouse4th',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse4th',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse3rd',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList'),
        ),
        migrations.AddField(
            model_name='completedcouse3rd',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse3rd',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse2nd',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList'),
        ),
        migrations.AddField(
            model_name='completedcouse2nd',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse2nd',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse1st',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList'),
        ),
        migrations.AddField(
            model_name='completedcouse1st',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse1st',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='applyingcourse',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList'),
        ),
        migrations.AddField(
            model_name='applyingcourse',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile'),
        ),
    ]
