# Generated by Django 2.0 on 2018-01-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_semesterselection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semesterselection',
            options={'verbose_name': 'SemesterSelection'},
        ),
    ]
