# Generated by Django 2.0 on 2018-01-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180126_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semesterselection',
            options={'verbose_name': 'Semester Selection', 'verbose_name_plural': "Semester's Selection"},
        ),
    ]
