# Generated by Django 2.0 on 2018-01-27 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_studentprofile_date_of_birth'),
        ('course', '0004_auto_20180126_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedCouse1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('section', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Completed 1st sem courses',
            },
        ),
        migrations.CreateModel(
            name='CompletedCouse2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('section', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Completed 2nd sem courses',
            },
        ),
        migrations.CreateModel(
            name='CompletedCouse3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('section', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Completed 3rd sem courses',
            },
        ),
        migrations.CreateModel(
            name='CompletedCouse4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('section', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Completed 4th sem courses',
            },
        ),
        migrations.CreateModel(
            name='CompletedCouse5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('section', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Completed 5th sem courses',
            },
        ),
        migrations.CreateModel(
            name='CompletedCouse6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('section', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Completed 6th sem courses',
            },
        ),
        migrations.CreateModel(
            name='CompletedCouse7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('section', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Completed 7th sem courses',
            },
        ),
        migrations.CreateModel(
            name='CompletedCouse8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('semester', models.CharField(blank=True, max_length=32, null=True)),
                ('section', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Completed 8th sem courses',
            },
        ),
        migrations.RemoveField(
            model_name='completedcouse1st',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse1st',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse1st',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse2nd',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse2nd',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse2nd',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse3rd',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse3rd',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse3rd',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse4th',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse4th',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse4th',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse5th',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse5th',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse5th',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse6th',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse6th',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse6th',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse7th',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse7th',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse7th',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse8th',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse8th',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='completedcouse8th',
            name='teacher_id',
        ),
        migrations.AlterModelOptions(
            name='applyingcourse',
            options={'verbose_name_plural': 'Applying Courses'},
        ),
        migrations.AlterModelOptions(
            name='courselist',
            options={'verbose_name_plural': 'All courses List'},
        ),
        migrations.AlterModelOptions(
            name='takencourse',
            options={'verbose_name_plural': 'Taken Courses'},
        ),
        migrations.AddField(
            model_name='applyingcourse',
            name='semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='courselist',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='takencourse',
            name='semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='CompletedCouse1st',
        ),
        migrations.DeleteModel(
            name='CompletedCouse2nd',
        ),
        migrations.DeleteModel(
            name='CompletedCouse3rd',
        ),
        migrations.DeleteModel(
            name='CompletedCouse4th',
        ),
        migrations.DeleteModel(
            name='CompletedCouse5th',
        ),
        migrations.DeleteModel(
            name='CompletedCouse6th',
        ),
        migrations.DeleteModel(
            name='CompletedCouse7th',
        ),
        migrations.DeleteModel(
            name='CompletedCouse8th',
        ),
        migrations.AddField(
            model_name='completedcouse8',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList'),
        ),
        migrations.AddField(
            model_name='completedcouse8',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse8',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse7',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList'),
        ),
        migrations.AddField(
            model_name='completedcouse7',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse7',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse6',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList'),
        ),
        migrations.AddField(
            model_name='completedcouse6',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse6',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse5',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList'),
        ),
        migrations.AddField(
            model_name='completedcouse5',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse5',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse4',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList'),
        ),
        migrations.AddField(
            model_name='completedcouse4',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse4',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse3',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList'),
        ),
        migrations.AddField(
            model_name='completedcouse3',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse3',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse2',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList'),
        ),
        migrations.AddField(
            model_name='completedcouse2',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse2',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse1',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseList'),
        ),
        migrations.AddField(
            model_name='completedcouse1',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentProfile'),
        ),
        migrations.AddField(
            model_name='completedcouse1',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
    ]
