# Generated by Django 2.0 on 2018-01-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20180127_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyingcourse',
            old_name='course_id',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='takencourse',
            old_name='course_id',
            new_name='course_code',
        ),
    ]
