# Generated by Django 2.0 on 2018-01-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20180127_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedcouse1',
            old_name='course_id',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='completedcouse2',
            old_name='course_id',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='completedcouse3',
            old_name='course_id',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='completedcouse4',
            old_name='course_id',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='completedcouse5',
            old_name='course_id',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='completedcouse6',
            old_name='course_id',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='completedcouse7',
            old_name='course_id',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='completedcouse8',
            old_name='course_id',
            new_name='course_code',
        ),
    ]
