# Generated by Django 2.0 on 2018-01-27 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_studentprofile_date_of_birth'),
        ('course', '0007_auto_20180127_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyingcourse',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='takencourse',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
    ]
