# Generated by Django 2.0 on 2018-01-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20180127_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='takencourse',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
