# Generated by Django 2.0 on 2018-01-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_takencourse_gpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselist',
            name='id',
        ),
        migrations.AlterField(
            model_name='courselist',
            name='course_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
