# Generated by Django 2.0 on 2018-01-29 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20180130_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courselist',
            name='course_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
