# Generated by Django 2.0 on 2018-01-29 19:54

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20180130_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselist',
            name='id',
        ),
        migrations.AlterField(
            model_name='courselist',
            name='course_code',
            field=models.CharField( max_length=10),
            preserve_default=False,
        ),
    ]
