# Generated by Django 2.0 on 2018-01-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20180130_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        
        migrations.AlterField(
            model_name='courselist',
            name='course_code',
            field=models.CharField(max_length=10),
        ),
    ]
