# Generated by Django 2.0 on 2018-01-29 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20180130_0208'),
        ('course', '0013_auto_20180130_0242'),
    ]

    operations = [
    ]
