# Generated by Django 2.0 on 2018-01-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20180130_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselist',
            name='course_code',
            field=models.CharField(max_length=20),
        ),
    ]
