# Generated by Django 2.0 on 2018-02-13 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_section2am_section2bm_section2cm_section2dm_section3am_section3bm_section3cm_section3dm_section4am_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section1am',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AlterField(
            model_name='section1bm',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AlterField(
            model_name='section1cm',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AlterField(
            model_name='section1dm',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AlterField(
            model_name='section2am',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AlterField(
            model_name='section2bm',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AlterField(
            model_name='section2cm',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AlterField(
            model_name='section2dm',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AlterField(
            model_name='section3am',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AlterField(
            model_name='section3bm',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AlterField(
            model_name='section3cm',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AlterField(
            model_name='section3dm',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AlterField(
            model_name='section4am',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AlterField(
            model_name='section4bm',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AlterField(
            model_name='section4cm',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
        migrations.AlterField(
            model_name='section4dm',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TeacherProfile'),
        ),
    ]
