# Generated by Django 2.0 on 2018-03-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_auto_20180213_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='section1am',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='section1bm',
            name='semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='section1bm',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='section1cm',
            name='semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='section1cm',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='section1dm',
            name='semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='section1dm',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='section2am',
            name='semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='section2am',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='section2bm',
            name='semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='section2bm',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='section2cm',
            name='semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='section2cm',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='section2dm',
            name='semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='section2dm',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='section3am',
            name='semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='section3am',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='section3bm',
            name='semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='section3bm',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='section3cm',
            name='semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='section3cm',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='section3dm',
            name='semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='section3dm',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='section4am',
            name='semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='section4am',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='section4bm',
            name='semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='section4bm',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='section4cm',
            name='semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='section4cm',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='section4dm',
            name='semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='section4dm',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], default='REGULAR', max_length=10),
        ),
    ]
