# Generated by Django 2.0 on 2018-03-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0004_auto_20180302_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='section1am',
            name='semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
